# Generated by Django 5.1.5 on 2025-01-25 17:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('footprint', '0003_category_product_purchase_userprofile'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
    ]
